# original prezto zshrc
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc"
fi

path+=("${ZDOTDIR:-$HOME}/bin")
path+=("${ZDOTDIR:-$HOME}/.local/bin")

# z
source "${ZDOTDIR:-$HOME}/.zz/z.sh"

# virtualenvwrapper
# export WORKON_HOME=$HOME/.virtualenvs
# source /usr/bin/virtualenvwrapper.sh
